# Generated by Django 5.1.6 on 2025-04-09 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sca_app', '0014_remove_company_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='vehicle_number',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
